[Interface]
PrivateKey = wAUVTA9QAU9Tx0V4/nvMJmQn04S0mRNBi3E88dYpYHA=
Address = 100.1.1.1/32, fdac::1/128
ListenPort = 41194

[Peer]
PublicKey = vF/C2NJTnLGnizJREHUDRex25np3XQcJTiXD+6oxmkc=
AllowedIPs = 100.1.2.2/32, 100.1.2.3/32, fdac::2/128
Endpoint = 127.0.0.1:41195
PersistentKeepalive = 10
