[Interface]
PrivateKey = OH1ujo3vq8XDYHnISnQa19wDs5tHbD+U062Erd89HE0=
Address = 100.1.2.2/32, fdac::2/128
ListenPort = 41195

[Peer]
PublicKey = VFnog4JuqHtx1MhHn9wpyphY5N1vTVT7wxx9rmzoRwg=
AllowedIPs = 100.1.1.1/32, fdac::1/128
Endpoint = 127.0.0.1:41194
PersistentKeepalive = 10
