FROM golang:1.26-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY tools/mock.go .

ENV CGO_ENABLED=0

RUN go build -o /qkd-simulator mock.go

FROM alpine:latest

RUN apk add --no-cache bash iproute2 iputils

COPY --from=builder /qkd-simulator /usr/local/bin/qkd-simulator

CMD ["/usr/local/bin/qkd-simulator"]
